variable "identifier" {
  description = "RDS instance identifier (caller applies workspace suffix)."
  type        = string
}

variable "vpc_id" {
  description = "VPC the database runs in."
  type        = string
}

variable "subnet_ids" {
  description = "Private subnet IDs for the DB subnet group."
  type        = list(string)
}

variable "allowed_security_group_ids" {
  description = "Security group IDs allowed to reach Postgres on 5432 (e.g. EKS node SG)."
  type        = list(string)
  default     = []
}

variable "engine_version" {
  description = "PostgreSQL engine version."
  type        = string
  default     = "16"
}

variable "family" {
  description = "DB parameter group family."
  type        = string
  default     = "postgres16"
}

variable "major_engine_version" {
  description = "Major engine version for the option group."
  type        = string
  default     = "16"
}

variable "instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t3.medium"
}

variable "allocated_storage" {
  description = "Initial allocated storage (GiB)."
  type        = number
  default     = 50
}

variable "max_allocated_storage" {
  description = "Storage autoscaling ceiling (GiB)."
  type        = number
  default     = 200
}

variable "db_name" {
  description = "Initial database name."
  type        = string
  default     = "quantvista"
}

variable "username" {
  description = "Master username."
  type        = string
  default     = "quantvista_admin"
}

variable "password" {
  description = "Master password (generated by caller; stored in Secrets Manager)."
  type        = string
  sensitive   = true
}

variable "multi_az" {
  description = "Deploy a standby in another AZ. Enable for production."
  type        = bool
  default     = false
}

variable "backup_retention_period" {
  description = "Automated backup retention in days."
  type        = number
  default     = 7
}

variable "deletion_protection" {
  description = "Block deletion of the instance. Enable for production."
  type        = bool
  default     = false
}

variable "skip_final_snapshot" {
  description = "Skip the final snapshot on destroy. Set false for production."
  type        = bool
  default     = true
}

variable "tags" {
  description = "Tags applied to database resources."
  type        = map(string)
  default     = {}
}
