/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — dependency-free so it stays green during boot.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stocks Endpoint
         * @description Browse the universe: filter by market/sector/cap + free-text ``q``, keyset-paginated.
         */
        get: operations["list_stocks_endpoint_api_v1_stocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock Endpoint
         * @description Master + latest snapshot for ``symbol`` (cached, TTL-backstopped).
         */
        get: operations["get_stock_endpoint_api_v1_stocks__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scores/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Score Endpoint
         * @description A stock's composite + sub-scores as of ``as_of`` (default latest).
         */
        get: operations["get_score_endpoint_api_v1_scores__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scores/{symbol}/decomposition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Decomposition Endpoint
         * @description Per-factor contributions that sum to the composite (US-02).
         */
        get: operations["get_decomposition_endpoint_api_v1_scores__symbol__decomposition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rankings Endpoint
         * @description Composite-desc leaderboard, truncated to the tenant's ``universe_scores_top`` quota.
         */
        get: operations["get_rankings_endpoint_api_v1_rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screener": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Screen Endpoint
         * @description Filter/sort the universe by any allow-listed factor/fundamental.
         */
        post: operations["screen_endpoint_api_v1_screener_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Screens Endpoint */
        get: operations["list_screens_endpoint_api_v1_screens_get"];
        put?: never;
        /**
         * Create Screen Endpoint
         * @description Save a screen, tier-limited by the ``saved_screens`` entitlement.
         */
        post: operations["create_screen_endpoint_api_v1_screens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screens/{screen_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Screen Endpoint */
        delete: operations["delete_screen_endpoint_api_v1_screens__screen_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts Endpoint */
        get: operations["list_alerts_endpoint_api_v1_alerts_get"];
        put?: never;
        /**
         * Create Alert Endpoint
         * @description Create an alert rule, tier-limited by the ``alerts`` entitlement.
         */
        post: operations["create_alert_endpoint_api_v1_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Alert Endpoint */
        delete: operations["delete_alert_endpoint_api_v1_alerts__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notifications Endpoint
         * @description The current user's recent notifications (newest first).
         */
        get: operations["list_notifications_endpoint_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Read Endpoint
         * @description Mark all of the current user's unread notifications read; returns the count updated.
         */
        post: operations["mark_read_endpoint_api_v1_notifications_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stock News Endpoint
         * @description Recent news tagged to ``symbol``, newest-first, within the plan's history window.
         */
        get: operations["stock_news_endpoint_api_v1_stocks__symbol__news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Market News Endpoint
         * @description Market-wide latest news (India-source-first), within the plan's history window.
         */
        get: operations["market_news_endpoint_api_v1_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertConditionSchema */
        AlertConditionSchema: {
            /** Metric */
            metric: string;
            /**
             * Op
             * @enum {string}
             */
            op: "gte" | "lte" | "gt" | "lt" | "eq";
            /** Value */
            value: number;
        };
        /** AlertRule */
        AlertRule: {
            /** Id */
            id: string;
            /** Scope */
            scope: string;
            /** Target Id */
            target_id: string;
            /** Target Symbol */
            target_symbol: string | null;
            /** Condition */
            condition: {
                [key: string]: unknown;
            };
            /** Channel */
            channel: string;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
        };
        /** CreateAlertRequest */
        CreateAlertRequest: {
            /**
             * Scope
             * @enum {string}
             */
            scope: "stock" | "portfolio";
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            condition: components["schemas"]["AlertConditionSchema"];
            /**
             * Channel
             * @enum {string}
             */
            channel: "email" | "in_app";
        };
        /** DecompositionResponse */
        DecompositionResponse: {
            /** Symbol */
            symbol: string;
            /** As Of */
            as_of: string;
            /** Composite */
            composite: number;
            /** Sum Of Contributions */
            sum_of_contributions: number;
            /** Factors */
            factors: components["schemas"]["FactorContribution"][];
        };
        /** Envelope[AlertRule] */
        Envelope_AlertRule_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["AlertRule"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[DecompositionResponse] */
        Envelope_DecompositionResponse_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["DecompositionResponse"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[MeResponse] */
        Envelope_MeResponse_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["MeResponse"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[SavedScreen] */
        Envelope_SavedScreen_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["SavedScreen"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[ScoreResponse] */
        Envelope_ScoreResponse_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["ScoreResponse"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[StockDetail] */
        Envelope_StockDetail_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["StockDetail"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[TokenResponse] */
        Envelope_TokenResponse_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["TokenResponse"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[dict[str, int]] */
        Envelope_dict_str__int__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: {
                [key: string]: number;
            } | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[dict[str, str]] */
        Envelope_dict_str__str__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: {
                [key: string]: string;
            } | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[AlertRule]] */
        Envelope_list_AlertRule__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["AlertRule"][] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[NewsItem]] */
        Envelope_list_NewsItem__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["NewsItem"][] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[Notification]] */
        Envelope_list_Notification__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["Notification"][] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[RankingItem]] */
        Envelope_list_RankingItem__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["RankingItem"][] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[SavedScreen]] */
        Envelope_list_SavedScreen__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["SavedScreen"][] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[ScreenerRow]] */
        Envelope_list_ScreenerRow__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["ScreenerRow"][] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[StockListItem]] */
        Envelope_list_StockListItem__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["StockListItem"][] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Error */
        Error: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** FactorContribution */
        FactorContribution: {
            /** Factor Key */
            factor_key: string;
            /** Category */
            category: string;
            /** Raw Value */
            raw_value: number | null;
            /** Zscore */
            zscore: number | null;
            /** Percentile Sector */
            percentile_sector: number | null;
            /** Percentile Universe */
            percentile_universe: number | null;
            /** Contribution */
            contribution: number;
            /** As Of */
            as_of: string;
        };
        /** FilterClause */
        FilterClause: {
            /** Field */
            field: string;
            /** Op */
            op: string;
            /** Value */
            value: number | string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LatestSnapshot */
        LatestSnapshot: {
            /** Price Date */
            price_date: string | null;
            /** Close */
            close: number | null;
            /** Composite Score */
            composite_score: number | null;
            /** Fundamental Score */
            fundamental_score: number | null;
            /** Momentum Score */
            momentum_score: number | null;
            /** Quality Score */
            quality_score: number | null;
            /** Sentiment Score */
            sentiment_score: number | null;
            /** Risk Score */
            risk_score: number | null;
            /** Coverage */
            coverage: number | null;
            /** Model Version */
            model_version: string | null;
            /** Weights Version */
            weights_version: string | null;
            /** Pe */
            pe: number | null;
            /** Pb */
            pb: number | null;
            /** Roe */
            roe: number | null;
            /** Roce */
            roce: number | null;
            /** Debt Equity */
            debt_equity: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
            /** Tenant Id */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
            /** Role */
            role: string;
            /** Entitlements */
            entitlements: {
                [key: string]: unknown;
            };
        };
        /** NewsItem */
        NewsItem: {
            /** Id */
            id: string;
            /** Headline */
            headline: string;
            /** Summary */
            summary: string | null;
            /** Source */
            source: string | null;
            /** Source Url */
            source_url: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /** Notification */
        Notification: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Read At */
            read_at: string | null;
            /** Created At */
            created_at: string;
        };
        /** RankingItem */
        RankingItem: {
            /** Rank */
            rank: number;
            /** Symbol */
            symbol: string;
            /** Composite Score */
            composite_score: number | null;
            /** Coverage */
            coverage: number | null;
            /** Close */
            close: number | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name?: string | null;
        };
        /** SaveScreenRequest */
        SaveScreenRequest: {
            /** Name */
            name: string;
            criteria: components["schemas"]["ScreenCriteria"];
        };
        /** SavedScreen */
        SavedScreen: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Criteria */
            criteria: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
        };
        /** ScoreResponse */
        ScoreResponse: {
            /** Symbol */
            symbol: string;
            /** As Of */
            as_of: string;
            /** Fundamental */
            fundamental: number | null;
            /** Momentum */
            momentum: number | null;
            /** Quality */
            quality: number | null;
            /** Sentiment */
            sentiment: number | null;
            /** Risk */
            risk: number | null;
            /** Composite */
            composite: number;
            /** Coverage */
            coverage: number | null;
            /** Weights Version */
            weights_version: string;
            /** Model Version */
            model_version: string;
        };
        /**
         * ScreenCriteria
         * @description A runnable screener spec (a ``/screener`` body sans ``limit``/``cursor``).
         */
        ScreenCriteria: {
            /**
             * Market
             * @default NSE
             */
            market: string;
            /** Filters */
            filters?: components["schemas"]["FilterClause"][];
            /** Sort */
            sort?: string | null;
        };
        /** ScreenRequest */
        ScreenRequest: {
            /**
             * Universe
             * @default NIFTY200
             */
            universe: string;
            /**
             * Market
             * @default NSE
             */
            market: string;
            /** Filters */
            filters?: components["schemas"]["FilterClause"][];
            /** Sort */
            sort?: string | null;
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /** Cursor */
            cursor?: string | null;
        };
        /** ScreenerRow */
        ScreenerRow: {
            /** Symbol */
            symbol: string;
            /** Company Name */
            company_name: string;
            /** Sector */
            sector: string | null;
            /** Market Cap Bucket */
            market_cap_bucket: string | null;
            /** Market */
            market: string;
            /** Composite Score */
            composite_score: number | null;
            /** Fundamental Score */
            fundamental_score: number | null;
            /** Momentum Score */
            momentum_score: number | null;
            /** Quality Score */
            quality_score: number | null;
            /** Sentiment Score */
            sentiment_score: number | null;
            /** Risk Score */
            risk_score: number | null;
            /** Coverage */
            coverage: number | null;
            /** Pe */
            pe: number | null;
            /** Pb */
            pb: number | null;
            /** Roe */
            roe: number | null;
            /** Roce */
            roce: number | null;
            /** Debt Equity */
            debt_equity: number | null;
        };
        /** StockDetail */
        StockDetail: {
            /** Symbol */
            symbol: string;
            /** Company Name */
            company_name: string;
            /** Sector */
            sector: string | null;
            /** Industry */
            industry: string | null;
            /** Market Cap Bucket */
            market_cap_bucket: string | null;
            /** Market */
            market: string;
            /** Is Active */
            is_active: boolean;
            snapshot: components["schemas"]["LatestSnapshot"];
        };
        /** StockListItem */
        StockListItem: {
            /** Id */
            id: string;
            /** Symbol */
            symbol: string;
            /** Company Name */
            company_name: string;
            /** Sector */
            sector: string | null;
            /** Market Cap Bucket */
            market_cap_bucket: string | null;
            /** Market */
            market: string;
            /** Composite Score */
            composite_score: number | null;
            /** Close */
            close: number | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict_str__str__"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenResponse_"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict_str__str__"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MeResponse_"];
                };
            };
        };
    };
    list_stocks_endpoint_api_v1_stocks_get: {
        parameters: {
            query?: {
                market?: string;
                sector?: string | null;
                market_cap_bucket?: string | null;
                /** @description Search by symbol or company name */
                q?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_StockListItem__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_endpoint_api_v1_stocks__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StockDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_score_endpoint_api_v1_scores__symbol__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScoreResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_decomposition_endpoint_api_v1_scores__symbol__decomposition_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DecompositionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rankings_endpoint_api_v1_rankings_get: {
        parameters: {
            query?: {
                universe?: string;
                market?: string;
                as_of?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_RankingItem__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screen_endpoint_api_v1_screener_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ScreenerRow__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_screens_endpoint_api_v1_screens_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_SavedScreen__"];
                };
            };
        };
    };
    create_screen_endpoint_api_v1_screens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveScreenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SavedScreen_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_screen_endpoint_api_v1_screens__screen_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_endpoint_api_v1_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_AlertRule__"];
                };
            };
        };
    };
    create_alert_endpoint_api_v1_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AlertRule_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alert_endpoint_api_v1_alerts__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_endpoint_api_v1_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_Notification__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_endpoint_api_v1_notifications_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict_str__int__"];
                };
            };
        };
    };
    stock_news_endpoint_api_v1_stocks__symbol__news_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_NewsItem__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_news_endpoint_api_v1_news_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_NewsItem__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
