/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — dependency-free so it stays green during boot.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stocks Endpoint
         * @description Browse the universe: filter by market/sector/cap, keyset-paginated by symbol.
         */
        get: operations["list_stocks_endpoint_api_v1_stocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock Endpoint
         * @description Master + latest snapshot for ``symbol`` (cached, TTL-backstopped).
         */
        get: operations["get_stock_endpoint_api_v1_stocks__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scores/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Score Endpoint
         * @description A stock's composite + sub-scores as of ``as_of`` (default latest).
         */
        get: operations["get_score_endpoint_api_v1_scores__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scores/{symbol}/decomposition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Decomposition Endpoint
         * @description Per-factor contributions that sum to the composite (US-02).
         */
        get: operations["get_decomposition_endpoint_api_v1_scores__symbol__decomposition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rankings Endpoint
         * @description Composite-desc leaderboard, truncated to the tenant's ``universe_scores_top`` quota.
         */
        get: operations["get_rankings_endpoint_api_v1_rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DecompositionResponse */
        DecompositionResponse: {
            /** Symbol */
            symbol: string;
            /** As Of */
            as_of: string;
            /** Composite */
            composite: number;
            /** Sum Of Contributions */
            sum_of_contributions: number;
            /** Factors */
            factors: components["schemas"]["FactorContribution"][];
        };
        /** Envelope[DecompositionResponse] */
        Envelope_DecompositionResponse_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["DecompositionResponse"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[MeResponse] */
        Envelope_MeResponse_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["MeResponse"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[ScoreResponse] */
        Envelope_ScoreResponse_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["ScoreResponse"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[StockDetail] */
        Envelope_StockDetail_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["StockDetail"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[TokenResponse] */
        Envelope_TokenResponse_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["TokenResponse"] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[dict[str, str]] */
        Envelope_dict_str__str__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: {
                [key: string]: string;
            } | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[RankingItem]] */
        Envelope_list_RankingItem__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["RankingItem"][] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Envelope[list[StockListItem]] */
        Envelope_list_StockListItem__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["StockListItem"][] | null;
            error?: components["schemas"]["Error"] | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** Error */
        Error: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** FactorContribution */
        FactorContribution: {
            /** Factor Key */
            factor_key: string;
            /** Category */
            category: string;
            /** Raw Value */
            raw_value: number | null;
            /** Zscore */
            zscore: number | null;
            /** Percentile Sector */
            percentile_sector: number | null;
            /** Percentile Universe */
            percentile_universe: number | null;
            /** Contribution */
            contribution: number;
            /** As Of */
            as_of: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LatestSnapshot */
        LatestSnapshot: {
            /** Price Date */
            price_date: string | null;
            /** Close */
            close: number | null;
            /** Composite Score */
            composite_score: number | null;
            /** Fundamental Score */
            fundamental_score: number | null;
            /** Momentum Score */
            momentum_score: number | null;
            /** Quality Score */
            quality_score: number | null;
            /** Sentiment Score */
            sentiment_score: number | null;
            /** Risk Score */
            risk_score: number | null;
            /** Coverage */
            coverage: number | null;
            /** Model Version */
            model_version: string | null;
            /** Weights Version */
            weights_version: string | null;
            /** Pe */
            pe: number | null;
            /** Pb */
            pb: number | null;
            /** Roe */
            roe: number | null;
            /** Roce */
            roce: number | null;
            /** Debt Equity */
            debt_equity: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
            /** Tenant Id */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
            /** Role */
            role: string;
            /** Entitlements */
            entitlements: {
                [key: string]: unknown;
            };
        };
        /** RankingItem */
        RankingItem: {
            /** Rank */
            rank: number;
            /** Symbol */
            symbol: string;
            /** Composite Score */
            composite_score: number | null;
            /** Coverage */
            coverage: number | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name?: string | null;
        };
        /** ScoreResponse */
        ScoreResponse: {
            /** Symbol */
            symbol: string;
            /** As Of */
            as_of: string;
            /** Fundamental */
            fundamental: number | null;
            /** Momentum */
            momentum: number | null;
            /** Quality */
            quality: number | null;
            /** Sentiment */
            sentiment: number | null;
            /** Risk */
            risk: number | null;
            /** Composite */
            composite: number;
            /** Coverage */
            coverage: number | null;
            /** Weights Version */
            weights_version: string;
            /** Model Version */
            model_version: string;
        };
        /** StockDetail */
        StockDetail: {
            /** Symbol */
            symbol: string;
            /** Company Name */
            company_name: string;
            /** Sector */
            sector: string | null;
            /** Industry */
            industry: string | null;
            /** Market Cap Bucket */
            market_cap_bucket: string | null;
            /** Market */
            market: string;
            /** Is Active */
            is_active: boolean;
            snapshot: components["schemas"]["LatestSnapshot"];
        };
        /** StockListItem */
        StockListItem: {
            /** Symbol */
            symbol: string;
            /** Company Name */
            company_name: string;
            /** Sector */
            sector: string | null;
            /** Market Cap Bucket */
            market_cap_bucket: string | null;
            /** Market */
            market: string;
            /** Composite Score */
            composite_score: number | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict_str__str__"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenResponse_"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict_str__str__"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MeResponse_"];
                };
            };
        };
    };
    list_stocks_endpoint_api_v1_stocks_get: {
        parameters: {
            query?: {
                market?: string;
                sector?: string | null;
                market_cap_bucket?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_StockListItem__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_endpoint_api_v1_stocks__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StockDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_score_endpoint_api_v1_scores__symbol__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScoreResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_decomposition_endpoint_api_v1_scores__symbol__decomposition_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DecompositionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rankings_endpoint_api_v1_rankings_get: {
        parameters: {
            query?: {
                universe?: string;
                market?: string;
                as_of?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_RankingItem__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
