variable "name_prefix" {
  description = "Secrets Manager path prefix, e.g. \"quantvista/staging\" (caller applies workspace)."
  type        = string
}

# --- Database ----------------------------------------------------------------
variable "db_username" {
  description = "Database master username."
  type        = string
}

variable "db_password" {
  description = "Database master password (generated by caller)."
  type        = string
  sensitive   = true
}

variable "db_host" {
  description = "Database hostname."
  type        = string
}

variable "db_port" {
  description = "Database port."
  type        = number
  default     = 5432
}

variable "db_name" {
  description = "Database name."
  type        = string
}

# --- Redis -------------------------------------------------------------------
variable "redis_auth_token" {
  description = "Redis AUTH token (generated by caller)."
  type        = string
  sensitive   = true
}

variable "redis_host" {
  description = "Redis primary endpoint hostname."
  type        = string
}

variable "redis_port" {
  description = "Redis port."
  type        = number
  default     = 6379
}

# --- IRSA (External Secrets Operator) ----------------------------------------
variable "eks_oidc_provider_arn" {
  description = "EKS OIDC provider ARN (from the eks module)."
  type        = string
}

variable "eks_oidc_provider" {
  description = "EKS OIDC issuer host/path without https:// (from the eks module)."
  type        = string
}

variable "external_secrets_namespace" {
  description = "Kubernetes namespace running External Secrets Operator."
  type        = string
  default     = "external-secrets"
}

variable "external_secrets_service_account" {
  description = "Kubernetes service account External Secrets Operator runs as."
  type        = string
  default     = "external-secrets"
}

variable "tags" {
  description = "Tags applied to secret + IAM resources."
  type        = map(string)
  default     = {}
}
