variable "name" {
  description = "Replication group name (caller applies workspace suffix)."
  type        = string
}

variable "vpc_id" {
  description = "VPC the cache runs in."
  type        = string
}

variable "subnet_ids" {
  description = "Private subnet IDs for the cache subnet group."
  type        = list(string)
}

variable "allowed_security_group_ids" {
  description = "Security group IDs allowed to reach Redis on 6379 (e.g. EKS node SG)."
  type        = list(string)
  default     = []
}

variable "node_type" {
  description = "ElastiCache node type."
  type        = string
  default     = "cache.t3.micro"
}

variable "num_cache_clusters" {
  description = "Number of nodes (>= 2 enables automatic failover + multi-AZ)."
  type        = number
  default     = 2
}

variable "engine_version" {
  description = "Redis engine version."
  type        = string
  default     = "7.1"
}

variable "auth_token" {
  description = "Redis AUTH token (generated by caller; stored in Secrets Manager)."
  type        = string
  sensitive   = true
}

variable "tags" {
  description = "Tags applied to cache resources."
  type        = map(string)
  default     = {}
}
